[build-system]
requires = ["setuptools>=68.0", "wheel", "Cython>=3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "farms_app"
version = "0.1.18"
description = "GUI Application for neuromechanical simulations using FARMS"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">= 3.11"
dependencies = [
    "imgui_bundle",
    "pyopengl",
    "glfw",
    "numpy",
    "tqdm",
    "pyyaml",
    "rich",
    "h5py",
    "stevedore",
    "farms_core", # Needed for logging
]

classifiers = [
  "Development Status :: 4 - Beta",
  # Indicate who your project is intended for
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Artificial Life",
  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://farmsim.dev"
Documentation = "https://farmsim.dev"
Repository = "https://github.com/farmsim/farms_app.git"
Issues = "https://github.com/farmsim/farms_app/issues"
Changelog = "https://github.com/farmsim/farms_app/blob/main/CHANGELOG.md"

[project.optional-dependencies]
farms = [
    "farms_sim",
    "farms_mujoco",
    "farms_network",
    "farms_muscle",
]

[project.scripts]
farms-app = "farms_app.cli:main"

[tool.setuptools.packages.find]
where = ["."]  # Change this - look in current directory
include = ["farms_app*"]  # Include farms_app and subpackages

[tool.setuptools.package-data]
farms_app = [
   "assets/fonts/*.ttf",
   "assets/**/*"
]

[project.entry-points."farms.app.extension"]
status_bar = "farms_app.extensions.ui.status_bar:StatusBarExtension"
debug = "farms_app.extensions.ui.logger:DebugExtension"
farmsim = "farms_app.extensions.farmsim.extension:FARMSIMExtension"

# mujoco = "farms_app.extensions.custom.mujoco_impl:MuJoCoExtension"
# experimental = "farms_app.extensions.custom.experimental:ExperimentalExtension"
# network = "farms_app.extensions.custom.network:NetworkExtension"
# optimization = "farms_app.extensions.custom.optimization:OptimizationExtension"